// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uggpiurbwagnuhqpugna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnZ3BpdXJid2FnbnVocXB1Z25hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5ODc2NjQsImV4cCI6MjA1OTU2MzY2NH0.3xORUZ5X53a963DoxhQ5WWvbmL_vZUYodczAH2vB9f0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);